#move the name 
#
#
#
import os,time
i = os.system('cls')
print(" ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("#     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("#     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("#     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print(" ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")
time.sleep(0.5)
i = os.system('cls')
print("     ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("    #     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("    #     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("    #     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print("     ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")
time.sleep(0.5)
i = os.system('cls')
print("         ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("        #     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("        #     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("        #     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print("         ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")
time.sleep(0.5)
i = os.system('cls')
print("             ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("            #     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("            #     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("            #     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print("             ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")
time.sleep(0.5)
i = os.system('cls')
print("                 ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("                #     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("                #     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("                #     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print("                 ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")
time.sleep(0.5)
i = os.system('cls')
print("                     ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("                    #     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("                    #     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("                    #     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print("                     ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")
time.sleep(0.5)
i = os.system('cls')
print("                         ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("                        #     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("                        #     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("                        #     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print("                         ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")
time.sleep(0.5)
i = os.system('cls')
print("                             ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("                            #     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("                            #     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("                            #     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print("                             ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")
time.sleep(0.5)
i = os.system('cls')
print("                                 ###  #   #   #####  #####      #     #  #   #      #    #  #   #  #####")
print("                                #     #   #   #      #   #       #   #   #   #      #  #    #   #  #   #")
print("                                #     #####   #####  #   #         #     #   #      #       #   #  #   #")
print("                                #     #   #   #      #   #         #     #   #      #  #    #   #  #   #")
print("                                 ###  #   #   #####  #   #         #      ###       #    #   ###   #   #")


#rotate the picture
#thanks for LiPeng and CaoXinYu
#
i=0
for i in range(100):
    if i%2==0:
        os.system('cls')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('                                 #                              ')
        print('          ########################                              ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        print('                                                                ')
        time.sleep(0.1)
    else:
        os.system('cls')
        print('                                                              ')
        print('                                                              ')
        print('                                                              ')
        print('                                                              ')
        print('                                                              ')
        print('                                                              ')
        print('                                                              ')
        print('                                                              ')
        print('                                                              ')
        print('                                                              ')
        print('                               #######################        ')
        print('                                #                             ')
        print('                                #                             ')
        print('                                #                             ')
        print('                                #                             ')
        print('                                #                             ')
        print('                                #                             ')
        print('                                #                             ')
        print('                                #                             ')
        print('                                #                             ')
        print('                                                              ')
        print('                                                              ')
        time.sleep(0.1)
